# Generated by Django 3.0.7 on 2020-06-21 13:50

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('street', models.CharField(max_length=256, verbose_name='Strasse')),
                ('zip', models.CharField(max_length=10, verbose_name='PLZ')),
                ('city', models.CharField(max_length=256, verbose_name='Stadt')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('Privat', 'Privat'), ('Company', 'Company')], default='Privat', max_length=20)),
                ('name', models.CharField(help_text='Firmenname oder Vor- und Nachname', max_length=256)),
                ('email', models.EmailField(max_length=256)),
                ('salutation', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('key', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=256, verbose_name='Land')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Rechnung')),
                ('body', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('due', models.DateField(default=datetime.date.today, verbose_name='Fällig')),
                ('date', models.DateField(default=datetime.date.today, verbose_name='Datum')),
                ('conditions', models.CharField(max_length=256, verbose_name='Konditionen')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Address')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicePosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Titel')),
                ('body', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Menge')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Betrag CHF')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='backend.Invoice')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='contact',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='backend.Contact'),
        ),
        migrations.AddField(
            model_name='address',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.Country'),
        ),
    ]
